version: "3"

services:
  tourguide:
    image: guardians59/tourguide-image
    ports:
     - 8080:8080

  gpsutil:
    image: guardians59/ms-gpsutil-image
    ports:
     - 8081:8081

  rewardcentral:
    image: guardians59/ms-rewardcentral-image
    ports:
     - 8082:8082

  tripricer:
    image: guardians59/ms-trippricer-image
    ports:
     - 8083:8083

